const HARVESTERS_TO_SPAWN = 2;
const REMOTE_HARVESTER_EAST_TO_SPAWN = 6;
const REMOTE_HARVESTER_NORTH_TO_SPAWN = 1;
const WORKERS_TO_SPAWN = 1;
const MAINTENANCE_TO_SPAWN = 1;
const WALL_UPGRADERS_TO_SPAWN = 1;

const HOME_ROOM = 'W93S68';
const ROOM_TO_CLAIM = '';
const REMOTE_HARVEST_EAST_ROOM = 'W92S68';
const REMOTE_HARVEST_NORTH_ROOM = 'W93S67';
const ROOM_TO_ATTACK = 'W93S67';
const ATTACKERS_TO_SPAWN = 1;
const IS_FLEEING = false;


module.exports = {
    // Primary room creeps
    HARVESTERS_TO_SPAWN,
    WORKERS_TO_SPAWN,
    MAINTENANCE_TO_SPAWN,
    WALL_UPGRADERS_TO_SPAWN,

    // Home room
    HOME_ROOM,


    // Remote harvesting (east)
    REMOTE_HARVEST_EAST_ROOM,
    REMOTE_HARVESTER_EAST_TO_SPAWN,


    // Remote harvesting (north)
    REMOTE_HARVEST_NORTH_ROOM,
    REMOTE_HARVESTER_NORTH_TO_SPAWN,


    // Attackers
    ATTACKERS_TO_SPAWN,
    IS_FLEEING,
    ROOM_TO_ATTACK,

    // Claiming
    ROOM_TO_CLAIM
};