const HARVESTERS_TO_SPAWN = 3;
const REMOTE_HARVESTER_TO_SPAWN = 3;
const WORKERS_TO_SPAWN = 3;
const MAINTENANCE_TO_SPAWN = 2;
const WALL_UPGRADERS_TO_SPAWN = 1;


const HOME_ROOM = 'W93S68';
const REMOTE_HARVEST_ROOM = 'W92S68';


module.exports = {
    HARVESTERS_TO_SPAWN,
    WORKERS_TO_SPAWN,
    MAINTENANCE_TO_SPAWN,
    REMOTE_HARVESTER_TO_SPAWN,
    WALL_UPGRADERS_TO_SPAWN,

    HOME_ROOM,
    REMOTE_HARVEST_ROOM
};